
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: download dependency
      run: go mod tidy
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
#build Stage
  build:
    name: Build Artifact
    needs: Test
    
    runs-on: self-hosted
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
# push to docker file 

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: yezato/test-cicd:latest
