# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: download dependency
      run: go mod tidy
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
#build Stage
  build:
    name: Build Artifact
    needs: Test
    
    runs-on: self-hosted
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      
  #BUILD THE ARTIFACT
    - name: Upload GO Artifact
      uses: actions/upload-artifact@v2
      with:
    #set artifact name
        name: artifact_GO
        #From:
        path: /*.exe
